### ISSUE TITLE
Install NPMs

### ISSUE THREAD

**Issue by jdmiragliotta** [jdmiragliotta/relp#2]
- Express
- Express Handlebars
- Express-Session
- Body Parser
- Sequelize
- BCryptJS
- Passport
- PassportLocal – will change after Heroku Database set up
- MySQL

**Comment by jdmiragliotta** [comment]
@donghoonkim1226  @richendacodes I added all the above packages, please Pull down and run npm install so we are all in the same page. Please comment back when you are done - second commenter please close the issue.

**Comment by donghoonkim1226** [comment]
@jdmiragliotta npm packages have been installed.
