### ISSUE TITLE
Layouts Folder

### ISSUE THREAD

**Issue by jdmiragliotta** [jdmiragliotta/relp#7]
Add layouts folder inside views folder

**Comment by donghoonkim1226** [comment]
@jdmiragliotta @richendacodes - Sent up merge request.

**Comment by jdmiragliotta** [comment]
Awesome! Reviewed and merged. Please close issue after seeing this!

**Comment by jdmiragliotta** [comment]
@donghoonkim1226  ^^^^^^^^^

**Comment by donghoonkim1226** [comment]
@jdmiragliotta closed.
